DATALOADER:
  NUM_INSTANCE: 4 # 每个batch中每个identity的样本数目
  NUM_WORKERS: 4 # 加载数据的进程数目
  SAMPLER: 'softmax_triplet' # 采样方式，这里是 softmax_triplet，即使用 softmax 计算 loss 的权重和使用 triplet loss 计算 loss
DATASETS:
  COMBINEALL: False # 是否将所有数据集合并
  ROOT_DIR: '/media/sda/xyz/datasets' # 174数据集的根目录
#  ROOT_DIR: 'D:/code/track2_aicity_2021-master/lib/data'
#  ROOT_DIR: '/media/lab225-2/disk1/datasets' # 175数据集的根目录
  TEST: ('vehicleid') # 测试数据集的名称
  TRAIN: ('vehicleid') # 训练数据集的名称
  SEED: 0

INPUT:
  AUGMIX_PROB: 0.25 # 数据增强中 Augmix 的概率
  COLORJIT_PROB: 0.25 # 数据增强中 ColorJitter 的概率
  COLOR_SPACE: 'rgb' # 数据读入时的颜色空间，这里是 RGB
  CUTOFF_LONGTAILED: False # 是否截断尾部类别
  LONGTAILED_THR: 2 # 截断尾部类别时的阈值
  PADDING: 10 # 图像 padding 的大小
  PIXEL_MEAN: [0.485, 0.456, 0.406] # 像素均值
  PIXEL_STD: [0.229, 0.224, 0.225] # 像素标准差
  PROB: 0.5 # 数据增强中某些操作的概率
  RANDOM_AFFINE_PROB: 0.25 # 数据增强中 RandomAffine 的概率
  RANDOM_BLUR_PROB: 0.25 # 数据增强中 RandomBlur 的概率
  RANDOM_PATCH_PROB: 0.25 # 数据增强中 RandomPatch 的概率
  RE_PROB: 0.5 # ReID 数据增强的概率
  RE_SH: 0.4 # 数据增强的强度
  SIZE_TEST: [256, 256] # 测试图像的大小
  SIZE_TRAIN: [256, 256] # 训练图像的大小
  VERTICAL_FLIP_PROB: 0.0 # 数据增强中垂直翻转的概率
  HOGMask_PROB: 0.2
  HOGMask_THRESHOLD: 10
MODEL:
  DEVICE: 'cuda' # 使用的设备，这里是 cuda
  DEVICE_ID: "'2'" # 使用的 GPU 编号
  DROPOUT_PROB: 0.5 # Dropout 的概率
  EMBEDDING_DIM: 512 # 特征维度
  EMBEDDING_HEAD: 'fc' # embedding 的类型
  FC_WEIGHT_NORM: False # 是否对全连接层的权重进行归一化
  FROZEN_FEATURE_EPOCH: 0 # 冻结特征提取层的 epoch 数，即在前几个epoch中，只更新全连接层的参数，不更新卷积层的参数。
  GLOBAL_DIM: 2048 # Global branch 的维度
  ID_LOSS_TYPE: 'circle' # ID loss 的类型，这里是 circle
  ID_LOSS_WEIGHT: 1.0 # ID loss 的权重
  IF_LABELSMOOTH: 'on' # 是否使用标签平滑
  LAST_STRIDE: 1 # 最后一个残差块的步长
  LOCAL_DIM: 512 # Local branch 的维度
  METRIC_LOSS_TYPE: 'supconloss' # metric loss 的类型，这里是 triplet
  MODEL_TYPE: 'baseline' # 模型的类型，这里是 baseline
  NAME: 'resnet50_ibn_a' # 使用的 backbone
  NECK: 'bnneck' # 使用的 neck，这里是 bnneck，表示使用BatchNorm层的特征提取网络。
  POOLING_METHOD: 'GeM' # pooling 的方式，这里是 GeM，表示使用Generalized Mean Pooling。
  PRETRAIN_CHOICE: 'imagenet' # 预训练模型的选择，这里是 imagenet，表示使用在ImageNet上预训练的模型。
  # PRETRAIN_PATH: 'D:/code/track2_aicity_2021-master/lib/modeling/pretrained_ckpts/resnet50_ibn_a.pth.tar'
  PRETRAIN_PATH: '/media/sda/xyz/track_ori/lib/modeling/pretrained_ckpts/resnet50_ibn_a-d9d0bb7b.pth' # 178服务器预训练模型的路径
#  PRETRAIN_PATH: '/home/xyz/track/tools/output/resume.pth.tar'
  TRIPLET_LOSS_WEIGHT: 1.0 # Triplet损失的权重
OUTPUT_DIR: 'output/' # 输出结果保存的目录
SOLVER:
  BASE_LR: 0.00035 # 初始化学习率
  BIAS_LR_FACTOR: 1 # 偏置项学习率因子
  CENTER_LOSS_WEIGHT: 0.0005 # Center Loss的权重
  CENTER_LR: 0.5 # Center Loss的学习率
  CHECKPOINT_PERIOD: 50 # 保存checkpoint的间隔
  CLUSTER_MARGIN: 0.3 # 聚类间隔大小
  COSINE_MARGIN: 0.35 # Cosine Loss的间隔大小
  COSINE_SCALE: 64 # Cosine Loss的比例因子
  CYCLE_EPOCH: 30 # 学习率循环的周期
  EVAL_PERIOD: 1 # 验证模型参数的间隔
  FC_LR_FACTOR: 1 # 全连接层学习率因子
  FP16: False # 是否启用FP16训练
  FREEZE_BASE_EPOCHS: 0 # 卷积层参数冻结的轮次
  GAMMA: 0.1 # 学习率衰减因子
  HARD_EXAMPLE_MINING_METHOD: batch_hard # 困难样本挖掘方法，这里是batch_hard
  IMS_PER_BATCH: 64 # 每个批次中的图像数
  LOG_PERIOD: 50 # 日志打印间隔
  LR_SCHEDULER: 'cosine_step' # 学习率调度器的类型，这里是cosine_step
  MARGIN: 0.3 # Triplet Loss的间隔大小
  MAX_EPOCHS: 12 # 最大训练轮次
  MOMENTUM: 0.9 # 优化器的动量
  NO_BIAS_DECAY: False # 是否对偏置项进行权重衰减
  OPTIMIZER_NAME: 'Adam' # 优化器的名称，这里是Adam
  RANGE_ALPHA: 0 # Range Loss的参数
  RANGE_BETA: 1 # Range Loss的参数
  RANGE_K: 2 # Range Loss的参数
  RANGE_LOSS_WEIGHT: 1 # Range Loss的权重
  RANGE_MARGIN: 0.3 # Range Loss的间隔大小
  STEPS: (12, 20) # 学习率衰减的步骤
  WARMUP_FACTOR: 0.01 # 学习率预热的因子
  WARMUP_ITERS: 500 # 学习率预热的迭代次数
  WARMUP_METHOD: 'linear' # 学习率预热的方法，这里是线性预热
  WEIGHT_DECAY: 1e-06 # 权重衰减的因子
  WEIGHT_DECAY_BIAS: 1e-06 # 偏置项权重衰减的因子
  XBM_SIZE: 4 # 存储历史预测结果的缓冲区大小
TEST:
  ATTRIBUTES_RERANK: False # 是否使用属性信息进行重排。默认为False，即不使用属性信息进行重排。
  CAM_DIST_PATH: 'dists_test/cam_feat_distmat.npy' # 用于CAM重排的特征距离矩阵路径，默认值为'dists_test/cam_feat_distmat.npy'。
  DO_DBA: False # 是否进行动态背景自适应。默认为False，即不进行动态背景自适应
  DO_RERANK: True # 是否进行重排。默认为True，即进行重排
  FEAT_NORM: 'yes' # 特征是否归一化。默认为'yes'，即进行特征归一化
  FLIP_TEST: False # 是否进行水平翻转测试。默认为False，即不进行水平翻转测试
  IMS_PER_BATCH: 128 # 每个批次的图像数。默认为32
  NECK_FEAT: 'after' # 特征提取器中选择的neck特征类型。默认为'after'，即使用最后一层的输出特征
  ORI_DIST_PATH: 'dists_test/ori_feat_distmat.npy' # 用于原始特征进行重排的特征距离矩阵路径，默认值为'dists_test/ori_feat_distmat.npy'
  QUERY_EXPANSION: False # 是否使用查询扩展。默认为False，即不使用查询扩展
  RERANK_PARAM: [50, 15, 0.5] # 重排参数，格式为[re_rank_topk, re_rank_threshold, re_rank_weight]。默认为[50, 15, 0.5]。
  TRACK_AUG: False # 是否使用轨迹增强。默认为False，即不使用轨迹增强
  TRACK_RERANK: False # 是否进行轨迹重排。默认为False，即不进行轨迹重排
  USE_VOC: False # 是否使用VOC数据集进行重排。默认为False，即不使用VOC数据集进行重排
  WEIGHT: 'output/best.pth' #  模型权重文件的路径。默认为'output/best.pth'
  WRITE_RESULT: True # 是否将结果写入到文件中。默认为True，即将结果写入到文件中
