DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: 'softmax_triplet'
DATASETS:
  COMBINEALL: False
  ROOT_DIR: '/media/sda/xyz/datasets'
  TEST: ('veriwild')
  TRAIN: ('veriwild')
  SEED: 0

INPUT:
  AUGMIX_PROB: 0.25
  COLORJIT_PROB: 0.25
  COLOR_SPACE: 'rgb'
  CUTOFF_LONGTAILED: False
  LONGTAILED_THR: 2
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROB: 0.5
  RANDOM_AFFINE_PROB: 0.25
  RANDOM_BLUR_PROB: 0.25
  RANDOM_PATCH_PROB: 0.25
  RE_PROB: 0.5
  RE_SH: 0.4
  SIZE_TEST: [256,256]
  SIZE_TRAIN: [256,256]
  VERTICAL_FLIP_PROB: 0.0
  HOGMask_PROB: 0.2
  HOGMask_THRESHOLD: 30
MODEL:
  DEVICE: 'cuda'
  DEVICE_ID: "'0,1,2'"
  DROPOUT_PROB: 0.0
  EMBEDDING_DIM: 512
  EMBEDDING_HEAD: 'fc'
  FC_WEIGHT_NORM: False
  FROZEN_FEATURE_EPOCH: 0
  GLOBAL_DIM: 2048
  ID_LOSS_TYPE: 'circle'
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: 'on'
  LAST_STRIDE: 1
  LOCAL_DIM: 512
  METRIC_LOSS_TYPE: 'supconloss'
  CROSS_DISTAN_LOSS_TYPE: 'js'
  MODEL_TYPE: 'baseline'
  NAME: 'resnet50_ibn_a'
  NECK: 'bnneck'
  POOLING_METHOD: 'GeM'
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/path/of/your/resnet50_ibn_a-d9d0bb7b.pth'
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: 'output/'
SOLVER:
  BASE_LR: 0.00007
  BIAS_LR_FACTOR: 1
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 50
  CLUSTER_MARGIN: 0.3
  COSINE_MARGIN: 0.35
  COSINE_SCALE: 64
  CYCLE_EPOCH: 30
  EVAL_PERIOD: 1
  FC_LR_FACTOR: 1
  FP16: False
  FREEZE_BASE_EPOCHS: 0
  GAMMA: 0.1
  HARD_EXAMPLE_MINING_METHOD: batch_hard
  IMS_PER_BATCH: 64
  LOG_PERIOD: 50
  LR_SCHEDULER: 'cosine_step'
  MARGIN: 0.3
  MAX_EPOCHS: 24
  MOMENTUM: 0.9
  NO_BIAS_DECAY: False
  OPTIMIZER_NAME: 'Adam'
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_K: 2
  RANGE_LOSS_WEIGHT: 1
  RANGE_MARGIN: 0.3
  STEPS: (12, 20)
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 500
  WARMUP_METHOD: 'linear'
  WEIGHT_DECAY: 1e-06
  WEIGHT_DECAY_BIAS: 1e-06
  XBM_SIZE: 4
TEST:
  ATTRIBUTES_RERANK: False
  CAM_DIST_PATH: 'dists_test/cam_feat_distmat.npy'
  DO_DBA: False
  DO_RERANK: True
  FEAT_NORM: 'yes'
  FLIP_TEST: False
  IMS_PER_BATCH: 128
  NECK_FEAT: 'after'
  ORI_DIST_PATH: 'dists_test/ori_feat_distmat.npy'
  QUERY_EXPANSION: False
  RERANK_PARAM: [50, 15, 0.5]
  TRACK_AUG: False
  TRACK_RERANK: False
  USE_VOC: False
  WEIGHT: '/path/of/your/weight/'
  WRITE_RESULT: True
